### ISSUE TITLE
想请教一下，win11如何安装？

### ISSUE THREAD

**Issue by 1029CY** [Jackiu1997/pure_live#14]
![image](https://user-images.githubusercontent.com/52902760/217197859-486de021-e79c-406e-800c-2cae2d98e496.png)

**Comment by loa123** [comment]
win10 也同样出现此情况

**Comment by fiofo** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/121227162/217269132-11bfb3f9-6d4a-469d-a415-607f70d99d5c.png">
右键属性，然后按这样安装就可以用了

**Comment by fiofo** [comment]
本地安装证书

**Comment by Jackiu1997** [comment]
也可以改后缀名为.zip，直接解压，当绿色本地安装包
