### ISSUE TITLE
[bug]1.0.6全屏播放下会熄屏。

### ISSUE THREAD

**Issue by changyexing** [Jackiu1997/pure_live#2]
**描述错误**
在全屏播放时，系统会熄屏（锁屏）

**重现**
1. 全屏播放
2. 两分钟后屏幕熄灭（我个人设置的是两分钟锁屏）

**预期的行为**
修复此问题

**设备信息（请填写以下信息）：**
- 操作系统： Android13  MIUI14
- 版本： 1.0.6

**额外的背景**
在这里添加关于问题的任何其他背景。

[] 我已经阅读了相关内容并且描述准确

**Comment by Shereef01** [comment]
> **描述错误** 在全屏播放时，系统会熄屏（锁屏）
> 
> **重现**
> 
> 1. 全屏播放
> 2. 两分钟后屏幕熄灭（我个人设置的是两分钟锁屏）
> 
> **预期的行为** 修复此问题
> 
> **设备信息（请填写以下信息）：**
> 
> * 操作系统： Android13  MIUI14
> * 版本： 1.0.6
> 
> **额外的**背景 在这里添加关于问题的任何其他背景。
> 
> [] 我已经阅读了相关内容并且描述准确

你要在设置里选择屏幕常亮，就没有这个问题了
