### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by ssiop789** [Jackiu1997/pure_live#4]
**在提出问题时，请确保您已经阅读了以下内容**
 - [README](README.md)

 - [ISSUE](https://github.com/Jackiu1997/pure_live/issues?q=)

 - [如何有效地报告 Bug](https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html)

 - [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

在阅读完以上内容后，如果您仍然有问题，请删除自第一行加粗内容起至下一行加粗内容的所有文字，在最后一行的[]中填写x，然后描述问题。

**请勿删除自此行之后加粗的模板！**

**描述错误**
简明扼要地描述该错误是什么。

**重现**
重现该行为的步骤。
1. 转到 '....'
2. 点击 '....'
3. 向下滚动到 '....'
4. 看到错误

**预期的行为**
简明扼要地描述你期望发生的情况。

**屏幕截图**
如果适用，添加屏幕截图以帮助解释你的问题。

**设备信息（请填写以下信息）：**
- 操作系统： [例如：Windows]
- 版本： [例如：Windows 11 21H2]

**额外的背景**
在这里添加关于问题的任何其他背景。

[] 我已经阅读了相)关内容并且描述准确

![Screenshot_20230203-105927.jpg](https://user-images.githubusercontent.com/60536410/216502454-086997d1-d9e3-45b0-9bd1-7278bd4d4037.jpg)备份失败

**Comment by Jackiu1997** [comment]
备份问题已经修复，下版本更新
