### ISSUE TITLE
[request]能否增加个选项，各平台默认线路自行设置

### ISSUE THREAD

**Issue by KisThFir** [Jackiu1997/pure_live#51]
比如我这里斗鱼hw能看，但选择完线路，换个斗鱼同平台直播间又跳回默认的akm。b站默认的0线路只有大主播可以正常播放，小主播用的是1线路。

其实我更想要的是每个直播间线路记忆功能，但这个可能更难实现。

**Comment by ubidone** [comment]
+1 akm线路看不了

**Comment by Jackiu1997** [comment]
斗鱼流已经修复，暂时不考虑加入自定义记忆
