### ISSUE TITLE
[request] 软件主界面是不是不支持高刷

### ISSUE THREAD

**Issue by KDXYuuHi** [Jackiu1997/pure_live#54]
**请勿删除自此行之后加粗的模板！**

**你的功能请求是否与一个问题有关？请描述。**
清楚而简洁地描述问题是什么。例如：当[......]时，我感到[......]。

**描述你想要的解决方案**
对你希望发生的事情进行清晰、简明的描述。

**描述你所考虑的替代方案**
对你考虑过的任何替代性解决方案或功能进行清晰、简明的描述。

**补充**
在此添加关于该功能请求的任何其他背景或屏幕截图。

[X] 我已经阅读了相关内容并且描述准确

**Comment by KDXYuuHi** [comment]
不知道我的问题是不是模板
我在主界面和信息流里面感觉帧率不高 似乎是60帧 是软件单独不支持高刷嘛

**Comment by KDXYuuHi** [comment]
似乎软件锁定60hz 我的手机刷入了全局120hz的模块，这我有把握说是软件单独的问题。
![Screenshot_2023-04-17-14-29-39-56_b290cf9cc3b1cbf2201bfd68bd36ed45.jpg](https://user-images.githubusercontent.com/95617454/232402583-93708cd7-8191-4e9b-b11f-6460ec8704a1.jpg)

![Screenshot_2023-04-17-14-29-55-55_149003a2d400f6adb210d7e357a3a646.jpg](https://user-images.githubusercontent.com/95617454/232402589-c8f3987c-55d7-43a1-8a5b-bb63d611c13b.jpg)

**Comment by hsichien** [comment]
实测可以120Hz，可能是机型的问题

**Comment by KDXYuuHi** [comment]
> 实测可以120Hz，可能是机型的问题

你的机型是什么 我是一加11

**Comment by hsichien** [comment]
> > 实测可以120Hz，可能是机型的问题
> 
> 你的机型是什么 我是一加11

一加ACE 2V

**Comment by Jackiu1997** [comment]
一加手机高帧率问题暂时无法解决，是一加手机系统的问题
