### ISSUE TITLE
请问一下怎么设置cookie

### ISSUE THREAD

**Issue by M1NGc** [Jackiu1997/pure_live#62]
readmd 没看到样例

**Comment by MoRanHongChenLT** [comment]
登录b站，f12打开浏览器控制台，点开网络，再点开第一个含有spm_p_from的，然后就可以找到cookie，复制下来对应的cookie信息 ！在到pure live的设置里粘贴就行了！实在不行去B站找个教学视频!

**Comment by M1NGc** [comment]
ok 会了   没有说明不知道要spm_p_from这个cookie的值而已
