### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by ElmTran** [Jackiu1997/pure_live#75]
**描述错误**
偏好平台选择失效

**重现**
重现该行为的步骤。
1. 转到 'setting'
2. 点击 'platform reference'
3. 选择'douyu' 或者 'huya'
4. 在popular和areas并默认切换到选择平台。

**预期的行为**
正确的切换到相应平台。

**屏幕截图**
如果适用，添加屏幕截图以帮助解释你的问题。
![image](https://github.com/Jackiu1997/pure_live/assets/34189785/e46685fe-40f3-4150-846b-d572f60dc117)
![image](https://github.com/Jackiu1997/pure_live/assets/34189785/f030dcdb-1b03-42ee-9fc3-7ef81384928e)

**设备信息（请填写以下信息）：**
- 操作系统：Windows and Android
- 版本：Windows 11 22H2 and Android 12
- 移动端品牌：IQOO Neo3

**额外的背景**
在这里添加关于问题的任何其他背景。

[x] 我已经阅读了相关内容并且描述准确

**Comment by Jackiu1997** [comment]
已经修复
