### ISSUE TITLE
安卓端，看直播无常亮

### ISSUE THREAD

**Issue by SoulQAQ** [Jackiu1997/pure_live#82]
手机：redmi k30s
MIUI 版本：12.0.12 稳定版
Android版本：10

安卓端在看直播时，看一会进入无操作暗屏，需要点一下屏幕才可以亮起，是否需要加入一个看直播时常亮。

且切屏到后台再点进去会无法播放。

**Comment by GRGK0604** [comment]
设置里不是有直播常亮的开关吗

**Comment by SoulQAQ** [comment]
oh 我竟然没发现
