### ISSUE TITLE
[bug]电脑端无法安装

### ISSUE THREAD

**Issue by Yubfd** [Jackiu1997/pure_live#9]
关内容并且描述准确
![2023-02-05_163404](https://user-images.githubusercontent.com/123985945/216809396-805c039d-5712-4920-91ed-79325112a5cc.png)

**Comment by lyhhh6267** [comment]
+1

**Comment by Abraham-wy** [comment]
> 右键属性---数字签名---左键签名---详细信息---查看证书---安装证书---本地计算机---下一页---完成

我试过了还是不行呢？这是为什么

**Comment by gongchenyear** [comment]
> 右键属性---数字签名---左键签名---详细信息---查看证书---安装证书---本地计算机---下一页---完成

还是·不行·

**Comment by yangyinshanvip** [comment]
证书已安装还是不行
![image](https://user-images.githubusercontent.com/32298721/216937765-01d7829e-b8c1-4f5e-bf8d-9685479b897d.png)

**Comment by leyung** [comment]
> 证书已安装还是不行 ![image](https://user-images.githubusercontent.com/32298721/216937765-01d7829e-b8c1-4f5e-bf8d-9685479b897d.png)

参考链接：https://blog.csdn.net/qq_36237810/article/details/110238783

**Comment by Yubfd** [comment]
已经解决了

**Comment by Yubfd** [comment]
已经解决了，软件很棒




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月6日(星期一) 晚上6:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jackiu1997/pure_live] [bug]电脑端无法安装 (Issue #9)





  
证书已安装还是不行 
  
参考链接：https://blog.csdn.net/qq_36237810/article/details/110238783
